### ISSUE TITLE
small typo on path leads to 404 error

### ISSUE THREAD

**Issue by scottgruber** [indiana-university/rivet-docs#113]
## Describe the bug
Link saying "Contribute to Rivet" [on this page](https://rivet.iu.edu/blog/why-we-built-rivet/#why-not-bootstrap) leads to 404 error.

## Expected behavior
This link https://rivet.iu.edu/blog/why-we-built-rivet/contributing-to-rivet
Probably should be updated to this link
https://rivet.iu.edu/blog/contributing-to-rivet

## Relevant context (required)
> Not Found
> The requested URL /blog/why-we-built-rivet/contributing-to-rivet was not found on this server.

**Comment by illusivesunrae** [comment]
Released in PR #125.
