### ISSUE TITLE
Remove Composer files

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-docs#139]
A long time a go we were using Composer to manage a couple of php dependencies for tiny API service we built. That service was removed a long time ago, but the `composer.json` and `composer.lock` files are still being tracked in the repo.

We should remove these when possible. We should also double check to make sure that any Composer-releated commands are removed from the CI process if they still exist. I don't think they do, but it would be good to check as a part of this issue.

**Comment by illusivesunrae** [comment]
Released in PR #145.
