### ISSUE TITLE
CSS file not getting moved into public folder as part of default serve/watch task

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-docs#147]
## Background
The default `serve` task watches all .scss files and builds them into the `/static` directory, but the `serve` task is serving all built files (HTML, CSS, JS, etc.) from the `/public` directory and using BrowserSync to auto reload when any of the underlying files (inside `/public`) change.

## Steps to reproduce
Currently, if you save a `.scss` file while running the default `gulp serve` task the watch task is working and the sass re-compiles, but it is not being moved into the `/public` directory so browserSync is not updating i.e. you can't preview the changes to CSS.

If you save the HTML file that contains the markup associated with the new CSS (e.g. has the CSS class that you just added to a .scss file) then the compiled CSS file gets moved to the correct location and you are able to preview the updated CSS.

**Comment by scottanthonymurray** [comment]
@levimcg Can we mark this as `wontfix` as we'll be deprecating this site?

**Comment by levimcg** [comment]
yeah, that's fine with me. It was just an annoyance, not really a bug.
