### ISSUE TITLE
Add syntax highlighting for scss

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-docs#16]
While adding the documentation for the type scale Sass variables, I noticed that there is no support for .scss syntax highlighting. It would be nice to have as we are making an effort to document Sass usage in Rivet.

Here's the current output with no highlighting:
![image](https://user-images.githubusercontent.com/5590034/52294082-590d3c80-2946-11e9-9f6b-1fa3171ad868.png)

We are currently using [Highlight.js](https://highlightjs.org/) for syntax highlighting, and it _does_ support `.scss` highlighting, but I guess we didn't include it in the version we are using.

I would also be interested in looking at updating the highlight.js theme. They have one called _A11y_ that looks pretty nice, and I assume meets all WCAG 2.0 standards for contrast, etc.

https://highlightjs.org/static/demo/

**Comment by illusivesunrae** [comment]
Completed as part of PR #77.
