### ISSUE TITLE
Display the version number in which components were added to Rivet

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-docs#34]
It would be nice to add a field to the front matter of each component .md file that we can uses to display to users the version number where the component was added/introduced.

Something like:

```markdown
---
title: Box
asOf: 1.2.0
otherFrontMatter: ...
---
```

And then in the page template

```html
<h1>{{ .Title }}</h1>
<span>New in v{{ .Params.asOf }}</span>
```

This would be especially helpful until we can get around to publishing older versions of the docs.

**Comment by illusivesunrae** [comment]
Merged into master with #96.
