### ISSUE TITLE
Add deprecation notice to rvt-display-flex classes in display utilities

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-docs#42]
Now that we have implemented dedicated flexbox utilities, I think it makes sense to a deprecation notice to the older `.rvt-display-flex` and `.rvt-vertical-center` display utilities listed here:

https://rivet.iu.edu/components/utilities/display/#display-property-utilities

See this pull request for background info:

https://github.com/indiana-university/rivet-source/pull/75

**Comment by illusivesunrae** [comment]
[Proposed updates to documentation.](https://docs.google.com/document/d/1hoYWZPgapbURh6vbcJTgSZ0SGBcBrOnOfT_q6wTNfzQ/edit?usp=sharing)
