### ISSUE TITLE
Add documentation for .rvt-button__content class

### ISSUE THREAD

**Issue by illusivesunrae** [indiana-university/rivet-docs#49]
A new class name was created (`.rvt-button__content`), and an old one was deprecated (`.rvt-button__text`) in response to an[ issue on rivet-source](https://github.com/indiana-university/rivet-source/issues/58). Documentation will need to be updated to reflect this.

**Comment by scottanthonymurray** [comment]
Fixed in the `1.4.0` release: https://rivet.iu.edu/components/overlays/loading-indicator/#handling-button-text-display-while-in-the-loading-state
