### ISSUE TITLE
Update documentation for buttons to recommend that icons come before button text

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-docs#56]
We should update the documentation for how to use icons in button so that we recommend that icons come before text when using icons inside of buttons.

**Comment by basham** [comment]
Just stating what I said during the meeting:

If the label is describing the icon, the label should be placed immediately after the icon. This will be the most likely case.

If the icon indicates the behavior of the control, then the icon should be after the label. For example, `chevron-down` means _select an option_ and `circle-x` means _remove the option_.

**Comment by cwthomps** [comment]
I agree with that logic @basham. The one exception I can see is something like "< Back", which seems more intuitive than "Back <." So maybe directional icons should be used in a position that reinforces the direction.

**Comment by basham** [comment]
I'm not saying that all chevrons should be to the right of the label. In most cases, `chevron-down` will be to the right of the label. For your example, `Back` is the label for `chevron-left`, and therefore, it should be to the right of the icon. It's not sensible, but the closest I could imagine that `Back <` would mean is something like "`Back` will shift to the left upon clicking this button."

**Comment by illusivesunrae** [comment]
Released in PR #125.
