### ISSUE TITLE
Feedback on specific docs

### ISSUE THREAD

**Issue by jolamar** [indiana-university/rivet-docs#79]
I wanted to provide feedback on this specific page and was looking at the bottom for like a "was this page helpful" or "provide feedback" button. 

https://rivet.iu.edu/components/forms/select-input/

Anyways I wonder if we should include something about `selected` or `aria-selected` attributes.

**Comment by levimcg** [comment]
Thanks for opening this up @jolamar. I have been kicking around the idea of how we could make it easier for folks to create issues/give feedback on specific components/docs. Or, at least a direct link to the `.md` file on GitHub.

I think we need to do some more thinking on how best to do that.

**Comment by illusivesunrae** [comment]
We're closing this issue as there is not currently enough interest to pursue this.
