### ISSUE TITLE
Link to "Hidden content" doc

### ISSUE THREAD

**Issue by basham** [indiana-university/rivet-docs#84]
Devs are referencing the Rivet components and using them as patterns for their own work. They are noticing how Rivet uses the `aria-hidden` attribute and `.rvt-sr-only` class utility, but those aren't the only methods that we should use. We should provide additional documentation outlining these methods and use cases.

Recommendations:

1. Reference the [*Hidden content* doc on the UX site](https://ux.iu.edu/accessibility/hiding-content/) in the "Screen reader only" and "Visually hidden labels example" sections of the [*Display* doc page](https://rivet.iu.edu/components/utilities/display/).
2. Move the "Screen reader only" and "Visually hidden labels example" sections to the [*Visibility* doc page](https://rivet.iu.edu/components/utilities/visibility/). This seems to be a more logical place to keep the content.

**Comment by levimcg** [comment]
Good call. I made the decision early on to use `aria-hidden` as the method to show/hide content (both visually and from screen readers) with JavaScript. Moving forward we'll definitely default to using the `hidden` attribute for showing and hiding things.

I'll pull this on into the backlog so we can get it prioritized.

**Comment by illusivesunrae** [comment]
Pulled into master in PR #106.
